### PR TITLE
Upgrade to maven-enforcer-api 3.0.0

### LINKED ISSUE #56: Not compatible with Maven Enforcer Plugin 3.0.0?
It seems these rules don't work with the Maven Enforcer Plugin 3.0.0. I have a [reproducer project](https://github.com/mthmulders/mep-oss-issue) available. When I build it using Maven 3.8.2 with `mvn verify -e`, this stacktrace appears:

```console
Caused by: java.lang.NoSuchMethodError: 'org.apache.maven.shared.dependency.graph.DependencyNode org.apache.maven.shared.dependency.graph.DependencyGraphBuilder.buildDependencyGraph(org.apache.maven.project.MavenProject, org.apache.maven.artifact.resolver.filter.ArtifactFilter)'
    at org.sonatype.ossindex.maven.enforcer.BanVulnerableDependencies$Task.resolveDependencies (BanVulnerableDependencies.java:315)
    at org.sonatype.ossindex.maven.enforcer.BanVulnerableDependencies$Task.run (BanVulnerableDependencies.java:190)
    at org.sonatype.ossindex.maven.enforcer.BanVulnerableDependencies.execute (BanVulnerableDependencies.java:142)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:200)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

### PR DESCRIPTION
**Pull request by bkrahl-nli**
Breaks Java 1.7 compatibility. Is this still a hard requirement?

Closes #56 

Inspired by changes in https://github.com/mojohaus/extra-enforcer-rules/commit/d380fe56a7317a237bbce5b94fbab7f4581d3d1b

### CODE REVIEW

**Comment by DarthHater** [comment]
@bkrahl-nli can you go to: https://sonatypecla.herokuapp.com/sign-cla and sign the CLA for us? Once you have done so let me know!

**Comment by bkrahl-nli** [comment]
Hi @DarthHater! I signed the CLA.

**Comment by DarthHater** [comment]
@bkrahl-nli awesome. Next step, just some help on testing this out would be nice. I'm the second string on this project, but I'd like to help verify it's all gravy. Do you have an example I can follow?

**Comment by bkrahl-nli** [comment]
@DarthHater, sure. I created a little demo project based on https://start.spring.io/. It requires JDK 8. And the build will fail since it has a dependency on log4j 2.15.0 with the incomplete fix for CVE-2021-44228 here for testing (low vulnerability).

https://github.com/bkrahl-nli/oss-vulnerability-check-demo

I would suggest that you clone it and build it first. It should fail since it can't find the `ossindex-maven-enforcer-rules` 3.1.1-SNAPSHOT dependency.

Afterwards checkout this pull request and trigger a `mvn clean install`. Now the `oss-vulnerability-check-demo` project should build and fail with a vulnerability warning.

I describe this in more detail in [README.md](https://github.com/bkrahl-nli/oss-vulnerability-check-demo/blob/master/README.md).

**Comment by bkrahl-nli** [comment]
@DarthHater can I further assist you on testing this change?

File: enforcer-rules/src/main/java/org/sonatype/ossindex/maven/enforcer/BanVulnerableDependencies.java [hunk 1]
```diff
@@ -312,7 +314,12 @@ private void maybeApplyProxy(final OssindexClientConfiguration clientConfigurati
         artifactFilter = new CumulativeScopeArtifactFilter(scopes);
       }
 
-      DependencyNode node = graphBuilder.buildDependencyGraph(project, artifactFilter);
+      ProjectBuildingRequest buildingRequest =
+              new DefaultProjectBuildingRequest( session.getProjectBuildingRequest() );
+      buildingRequest.setProject( project );
+
+      buildingRequest.setProject( project );
```
Comment (jdillon) [inline enforcer-rules/src/main/java/org/sonatype/ossindex/maven/enforcer/BanVulnerableDependencies.java:321]: duplicate call to setProject() ?

Comment (bkrahl-nli) [reply enforcer-rules/src/main/java/org/sonatype/ossindex/maven/enforcer/BanVulnerableDependencies.java]: Thanks @jdillon! You are right. I removed the duplicate call.

**Comment by bkrahl-nli** [comment]
I updated the Maven dependencies and `ossindex-service-client` so that we don't rely on vulnerable `plexus-utils` 2.0.4 anymore as reported by sonartype-lift. I pushed it to a separate branch in commit bkrahl-nli/ossindex-maven@dacf3cba65a3bc80dd55d6de7453e5f7f1f46963.

@jdillon, should I added the above commit to this pull request too?

**Comment by DarthHater** [comment]
@bkrahl-nli I wouldn't mind if you did so!

**Comment by bkrahl-nli** [comment]
Is there anything I can do to help here?

**Review by ndonewar — APPROVED** [review]
@bkrahl-nli Sorry for the delay, and thank you for your contribution! I've tested these changes locally, and they look good.

Previously the output for building the test project was:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.516 s
[INFO] Finished at: 2022-01-26T15:09:06-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (vulnerability-checks) on project demo: Execution vulnerability-checks of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce: java.lang.NoSuchMethodError: 'org.apache.maven.shared.dependency.graph.DependencyNode org.apache.maven.shared.dependency.graph.DependencyGraphBuilder.buildDependencyGraph(org.apache.maven.project.MavenProject, org.apache.maven.artifact.resolver.filter.ArtifactFilter)'
```

With these changes, the output for building the test project is (as expected):
```
[WARNING] Rule 0: org.sonatype.ossindex.maven.enforcer.BanVulnerableDependencies failed with message:
Detected 1 vulnerable components:
  org.apache.logging.log4j:log4j-core:jar:2.15.0:compile; https://ossindex.sonatype.org/component/pkg:maven/org.apache.logging.log4j/log4j-core@2.15.0?utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1
    * [CVE-2021-45105] Apache Log4j2 versions 2.0-alpha1 through 2.16.0 (excluding 2.12.3) did not prot... (7.5); https://ossindex.sonatype.org/vulnerability/7cc258a5-d3ab-451f-bd27-415ae0e3b457?component-type=maven&component-name=org.apache.logging.log4j.log4j-core&utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1
    * [CVE-2021-45046] It was found that the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was i... (3.7); https://ossindex.sonatype.org/vulnerability/edaf092e-e7f3-4c69-8f01-a5c6fc44890a?component-type=maven&component-name=org.apache.logging.log4j.log4j-core&utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by astubbs** [comment]
Is there somewhere we can track the next release this will be included in?

**Comment by ndonewar** [comment]
> Is there somewhere we can track the next release this will be included in?

Normally a release would be created soon after such a change is merged. However, the project needed some attention to get the release out, as this project hadn't been released in a few years. The 3.2.0 release, which includes the changes in this PR, is out now:
https://github.com/sonatype/ossindex-maven/releases
